// automatically generated by the FlatBuffers compiler, do not modify

namespace NetworkedPhysics
{

using System;
using FlatBuffers;

public sealed class ClientConnectMessage : Table {
  public static ClientConnectMessage GetRootAsClientConnectMessage(ByteBuffer _bb) { return GetRootAsClientConnectMessage(_bb, new ClientConnectMessage()); }
  public static ClientConnectMessage GetRootAsClientConnectMessage(ByteBuffer _bb, ClientConnectMessage obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public ClientConnectMessage __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartClientConnectMessage(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<ClientConnectMessage> EndClientConnectMessage(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ClientConnectMessage>(o);
  }
};


}
