// automatically generated by the FlatBuffers compiler, do not modify

namespace NetworkedPhysics
{

public enum InputType : sbyte
{
 NONE = 0,
 Forward = 1,
 Backward = 2,
 Leftward = 3,
 Rightward = 4,
};


}
