// automatically generated by the FlatBuffers compiler, do not modify

namespace NetworkedPhysics
{

using System;
using FlatBuffers;

public sealed class KeepAliveMessage : Table {
  public static KeepAliveMessage GetRootAsKeepAliveMessage(ByteBuffer _bb) { return GetRootAsKeepAliveMessage(_bb, new KeepAliveMessage()); }
  public static KeepAliveMessage GetRootAsKeepAliveMessage(ByteBuffer _bb, KeepAliveMessage obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public KeepAliveMessage __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartKeepAliveMessage(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<KeepAliveMessage> EndKeepAliveMessage(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<KeepAliveMessage>(o);
  }
};


}
