// automatically generated by the FlatBuffers compiler, do not modify

namespace NetworkedPhysics
{

public enum MessageType : byte
{
 NONE = 0,
 MessageAck = 1,
 ClientConnectMessage = 2,
 ClientDisconnectMessage = 3,
 ClientInputMessage = 4,
 ServerSnapshotMessage = 5,
 ResetSimulationMessage = 6,
 KeepAliveMessage = 7,
};


}
