// automatically generated by the FlatBuffers compiler, do not modify

namespace NetworkedPhysics
{

using System;
using FlatBuffers;

public sealed class ResetSimulationMessage : Table {
  public static ResetSimulationMessage GetRootAsResetSimulationMessage(ByteBuffer _bb) { return GetRootAsResetSimulationMessage(_bb, new ResetSimulationMessage()); }
  public static ResetSimulationMessage GetRootAsResetSimulationMessage(ByteBuffer _bb, ResetSimulationMessage obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public ResetSimulationMessage __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartResetSimulationMessage(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<ResetSimulationMessage> EndResetSimulationMessage(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ResetSimulationMessage>(o);
  }
};


}
